# fly.toml app configuration file generated for muscle-memories on 2023-09-26T11:49:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muscle-memories"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
